### PR TITLE
Add BagIt sample data

### PR DESCRIPTION
**Pull request by j-panzer**
based on PPN595930174 (VD18 10246916)
file groups are reduced to PRESENTATION and GDZOCR to keep the data base simple

### CODE REVIEW

**Comment by kba** [comment]
Thanks!

ZIP contains a `_MACOSX` folder

Can we add `Ocrd-Identifier` and `Ocrd-Manifestation-Depth` (= 'partial') to the bag-info.txt (c.f. https://github.com/OCR-D/spec/pull/70). @VolkerHartmann can the repostiory metadata ingestor handle this?

I see the point of `fetch.txt` for test assets but for the serialization format we explicitly do not want fetch.txt. Maybe we could document this.

**Comment by kba** [comment]
I'm getting `HTTP 500` errors for some of the xml files, e.g. `http://gdz.sub.uni-goettingen.de/gdzocr/PPN595930174/00000035.xml`. @j-panzer Any idea what that is about?

**Comment by kba** [comment]
@j-panzer I updated the sample with SHA512 checksums for the files I could load (the XML files are empty) and extended the bag-info.txt a bit.

You can try to validate it against our BagIt profile by installing [OCR-D/core](https://github.com/ocr-d/core) and then running

```sh
ocrd zip validate --skip-unzip /path/to/assets/sample_bagit-with-fetch
```

**Comment by j-panzer** [comment]
The references are correct. There is a problem with the service (routing). We will correct this.

**Comment by kba** [comment]
> We solved the fulltext download problem :-)

Thx, it's loading now.

**Comment by kba** [comment]
I still do get empty response bodies for these files:

```sh
# find data -size 0
data/GDZOCR/00000004.xml
data/GDZOCR/00000318.xml
data/GDZOCR/00000312.xml
data/GDZOCR/00000316.xml
data/GDZOCR/00000322.xml
data/GDZOCR/00000326.xml
data/GDZOCR/00000324.xml
data/GDZOCR/00000314.xml
data/GDZOCR/00000320.xml
data/GDZOCR/00000310.xml
```

**Comment by j-panzer** [comment]
Ok, the API should export the OCR as TEI XML, but exports it preprocessed. We need to discuss and change this.

**Comment by kba** [comment]
> Ok, the API should export the OCR as TEI XML

I think these are HTML5 snippets:

```xml
head data/GDZOCR/00000014.xml

<p id="gdz-ID82">
  <span data-function="162,107,204,136">14</span>
  <span data-function="375,99,405,134">@</span>
  <span data-function="485,100,513,134">Ф</span>
  <span data-function="592,99,622,135">@</span>
</p>
<p id="gdz-ID83">
....
```

**Comment by kba** [comment]
`MIMETYPE="text/xml"` in the sample METS is not ideal. Preferably, `application/tei+xml` for TEI, `text/html` for HTML, `application/vnd.prima.page+xml` for PAGE.

@cneud BTW do we have a media type for abbyy finereader xml?

**Comment by cneud** [comment]
Currently we do not have a defined media type for FineReader Engine XML yet. How about using ``application/vnd.abbyy.fre+xml``?

**Pull request merged**
