### PR TITLE
sample gt bag

### PR DESCRIPTION
**Pull request by kba**

### CODE REVIEW

**Comment by wrznr** [comment]
However, this should -- in the long run -- not be the preferred GT format for `monkeybars`. We want PAGE here as well.

**Comment by kba** [comment]
`mollusc` will contain code to convert from PAGE to Line GT

**Comment by kba** [comment]
It's not ground truth as we provide it but ground truth in a format ready for use in training engines (line-based). See https://github.com/kba/ocr_linegt/tree/node/spec

Basically, it should be straightforward to convert our fine-grained ground truth to line ground truth, but they have different purposes. Whether it's feasible to convert on-the-fly or whether we'll need a repo for line gt will have to be seen.

**Comment by VolkerHartmann** [comment]
Ok, but we also have to provide metadata otherwise the trained model is useless.

**Comment by kba** [comment]
Provenance and bibliographic metadata (not yet) part of the spec. Again, the focus here is not versatile deeply described metadata but transcribed lines with images with technical metadata to be thrown onto a wrapper service (a mollusc, if you will), who feeds them to different engines (cephalopods, if you will.) :)

**Pull request merged**
