### PR TITLE
Remove duplicate files (fix issue #68)

### PR DESCRIPTION
**Pull request by stweil**
They only differ in lower case characters in their filename from existing files.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
@kba, do the CI checks require an update for this PR, too? It looks like they expect a certain number of files.

**Comment by stweil** [comment]
The bagit data for the modified `scribo-test` was fixed now and passes CI, but CircleCI fails with other data. That seems to be unrelated to my modification, so I think it can be merged.

**Comment by bertsky** [comment]
> but CircleCI fails with other data. That seems to be unrelated to my modification, so I think it can be merged.

Confirmed. This is the PAGE validator which has become stricter and now uncovers many small inconsistencies in the GT data. In this case:

```
Validating workspace kant_aufklaerung_1784 ... 
21:12:20.999 INFO ocrd.page_validator - Validating input file 'PAGE_0017_PAGE'
21:12:21.128 INFO ocrd.page_validator - Validating input file 'PAGE_0020_PAGE'
FAIL
<report valid="false">
  <error>INCONSISTENCY in TextRegion ID 'tl_8' of 'PAGE_0017_PAGE': coords '163,1055 917,1055 917,1124 163,1124' not within parent coords '109,1119 169,1117 166,1055 926,1054 926,1591 109,1591'</error>
  <error>INCONSISTENCY in TextRegion ID 'line_1478541568699_882' of 'PAGE_0017_PAGE': coords '849,1786 147,1786 147,1741 849,1741' not within parent coords '849,1787 108,1787 108,1749 849,1749'</error>
  <error>INCONSISTENCY in TextRegion ID 'line_1478541568699_881' of 'PAGE_0017_PAGE': coords '923,1786 849,1786 849,1741 923,1741' not within parent coords '925,1787 849,1787 849,1749 925,1749'</error>
```

In all 3 cases, the TextRegion is slightly undercut. Until I can offer @tboenig an automatic repair tool and he in turn can fix the non-trivial cases we all have to wait for better data or switch of the coordinate checker.

**Comment by bertsky** [comment]
I'd also say this can be merged.

**Comment by kba** [comment]
> switch off the coordinate checker

I did. Also tested with core and a few module projects and see no issues. Once CI passes, I'll merge.

**Pull request merged**
